language: java
jdk:
- openjdk8


addons:
  sonarcloud:
    organization: "jimciccio"
    token:
      secure: 14bbeb0400a52b734364c46dd1ca95a90496209e # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar