language: java
sudo: false

addons:
  sonarcloud:
    organization: "jimciccio"
    token:
      secure: "43ae381dd93666a206269f7a60af872f33b94eeb"

script: 
-mvn clean verify
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=jimciccio_BikerBikus
